# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi', models.IntegerField()),
                ('pm2_5', models.IntegerField()),
                ('pm10', models.IntegerField()),
                ('so2', models.IntegerField()),
                ('no2', models.IntegerField()),
                ('co', models.FloatField()),
                ('o3', models.IntegerField()),
                ('pollution_level', models.IntegerField()),
                ('primary_contaminant', models.CharField(max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 1, 4, 11, 0))),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=64, unique=True)),
                ('city_name', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aqi',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqi.City'),
        ),
    ]
